#!/usr/bin/env bash
# Installs this checkout's pre-commit hook the way users get it, from a local wheel instead of
# PyPI, and runs it on a sample repository. try-repo reads the committed tree, not the worktree.
#
#     pypi/hook-smoke.sh <directory holding a bonsai-lint wheel for this machine>
set -euo pipefail

wheels="$(cd "$1" && pwd)"
repo="$(cd "$(dirname "$0")/.." && pwd)"
sample="$(mktemp -d)"
trap 'rm -rf "$sample"' EXIT
export PIP_FIND_LINKS="$wheels" PRE_COMMIT_HOME="$sample/.pre-commit"

busy='function busy(a, b) {\n    if (a) { if (b) { return 1; } }\n    return 0;\n}\n'
mkdir -p "$sample/sub"
printf 'threshold = 2\n' >"$sample/bonsai-lint.toml"
printf 'threshold = 100\n' >"$sample/sub/bonsai-lint.toml"
printf '%b' "$busy" >"$sample/busy.ts"
printf 'function calm() { return 1; }\n' >"$sample/calm.ts"
printf 'declare const x: number;\n%b' "$busy" >"$sample/env.d.ts"
printf '// Code generated by protoc-gen-go. DO NOT EDIT.\n\npackage p\n\nfunc busy(a, b bool) int {\n\tif a {\n\t\tif b {\n\t\t\treturn 1\n\t\t}\n\t}\n\treturn 0\n}\n' >"$sample/gen.go"
# shellcheck disable=SC2016 # PHP's variables, not the shell's
printf '<?php\nfunction busy($a, $b) {\n    if ($a) { if ($b) { return 1; } }\n    return 0;\n}\n' >"$sample/sub/busy.php"
printf '# notes\n' >"$sample/README.md"
git -C "$sample" init --quiet
git -C "$sample" add --all
git -C "$sample" -c user.name=smoke -c user.email=smoke@localhost commit --quiet -m sample

expect() {
  local want="$1" needle="$2" output code=0
  shift 2
  output="$(cd "$sample" && uvx pre-commit@4.6.2 try-repo "$repo" bonsai-lint --files "$@" 2>&1)" || code=$?
  if [ "$code" != "$want" ] || ! grep -qF -- "$needle" <<<"$output"; then
    printf 'files %s: expected exit %s and "%s", got exit %s\n%s\n' "$*" "$want" "$needle" "$code" "$output"
    exit 1
  fi
  echo "ok: $* -> exit $code"
}

expect 1 "busy.ts:1  busy" busy.ts
expect 0 "Passed" calm.ts
expect 0 "Passed" env.d.ts gen.go
# The root config's threshold applies, not the undeclared one beside the file.
expect 1 "sub/busy.php:2  busy" sub/busy.php calm.ts
expect 0 "(no files to check)Skipped" README.md
