[package]
name = "bonsai-lang-vue"
description = "Vue single-file component support for bonsai-lint"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme = "../../README.md"

[dependencies]
bonsai-core = { workspace = true }
bonsai-lang-ts = { workspace = true }
tree-sitter = { workspace = true }
tree-sitter-html = { workspace = true }
tree-sitter-typescript = { workspace = true }

[dev-dependencies]
bonsai-testkit = { workspace = true }

[lints]
workspace = true
