//! A generated file is skipped outright, so the header rule must match what the Go toolchain
//! itself treats as generated, and nothing more.

use bonsai_lang_go::is_generated;

#[test]
fn the_standard_header_marks_a_file_generated() {
    assert!(is_generated(
        "// Code generated by protoc-gen-go. DO NOT EDIT.\n\npackage api\n"
    ));
}

#[test]
fn the_header_may_follow_build_constraints_and_other_comments() {
    let source = "//go:build linux\n\n// Copyright 2026.\n/* licence\n   text */\n// Code generated by stringer -type=Kind; DO NOT EDIT.\npackage p\n";
    assert!(is_generated(source));
}

#[test]
fn crlf_line_endings_still_match() {
    assert!(is_generated(
        "// Code generated by mockgen. DO NOT EDIT.\r\npackage p\r\n"
    ));
}

#[test]
fn a_byte_order_mark_or_indentation_before_the_header_is_ignored() {
    assert!(is_generated(
        "\u{feff}// Code generated by x. DO NOT EDIT.\npackage p\n"
    ));
    assert!(is_generated(
        "  // Code generated by x. DO NOT EDIT.\npackage p\n"
    ));
}

/// `go/ast.IsGenerated` compares the comment's text as written, so the line must end exactly at
/// `EDIT.`.
#[test]
fn trailing_whitespace_after_the_marker_does_not_count() {
    assert!(!is_generated(
        "// Code generated by x. DO NOT EDIT. \npackage p\n"
    ));
    assert!(!is_generated(
        "// Code generated by x. DO NOT EDIT.\t\npackage p\n"
    ));
}

#[test]
fn a_marker_after_the_package_clause_does_not_count() {
    assert!(!is_generated(
        "package p\n\n// Code generated by hand. DO NOT EDIT.\nfunc f() {}\n"
    ));
}

#[test]
fn only_a_line_comment_counts() {
    assert!(!is_generated(
        "/* Code generated by tool. DO NOT EDIT. */\npackage p\n"
    ));
}

#[test]
fn the_wording_must_be_exact() {
    assert!(!is_generated(
        "//Code generated by tool. DO NOT EDIT.\npackage p\n"
    ));
    assert!(!is_generated(
        "// Code generated by tool. Do not edit.\npackage p\n"
    ));
    assert!(!is_generated("// Code generated DO NOT EDIT.\npackage p\n"));
}

#[test]
fn a_handwritten_file_is_not_generated() {
    assert!(!is_generated("// Package p does things.\npackage p\n"));
    assert!(!is_generated(""));
}
