[package]
name = "bonsai-lang-php"
description = "PHP language support for bonsai-lint"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme = "../../README.md"
keywords = ["complexity", "php", "tree-sitter", "linter"]
categories = ["development-tools"]

[dependencies]
bonsai-core = { workspace = true }
tree-sitter = { workspace = true }
tree-sitter-php = { workspace = true }

[dev-dependencies]
bonsai-testkit = { workspace = true }

[lints]
workspace = true
