//! Java has no single generated-file convention, so the rule reads what the common generators
//! actually write before the first line of code: both "generated" and "do not edit".

use bonsai_lang_java::is_generated;

#[test]
fn a_protobuf_header_marks_a_file_generated() {
    let source = "// Generated by the protocol buffer compiler.  DO NOT EDIT!\n// NO CHECKED-IN PROTOBUF GENCODE\n// source: orders.proto\n\n// Protobuf Java Version: 4.28.2\npackage com.example.orders;\n";
    assert!(is_generated(source));
}

#[test]
fn a_multi_line_block_header_marks_a_file_generated() {
    let thrift = "/**\n * Autogenerated by Thrift Compiler (0.19.0)\n *\n * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING\n *  @generated\n */\npackage com.example;\n";
    let avro = "/**\n * Autogenerated by Avro\n *\n * DO NOT EDIT DIRECTLY\n */\npackage com.example.avro;\n";
    assert!(is_generated(thrift));
    assert!(is_generated(avro));
}

#[test]
fn a_javacc_header_marks_a_file_generated() {
    let source =
        "/* Generated By:JavaCC: Do not edit this line. Parser.java */\npackage com.example;\n";
    assert!(is_generated(source));
}

#[test]
fn crlf_a_byte_order_mark_and_any_case_still_match() {
    let source = "\u{feff}// generated by tooling\r\n// do NOT edit\r\npackage p;\r\n";
    assert!(is_generated(source));
}

#[test]
fn the_phrases_after_the_package_declaration_do_not_count() {
    let source =
        "package p;\n\n// Generated by the protocol buffer compiler.  DO NOT EDIT!\nclass C {}\n";
    assert!(!is_generated(source));
}

#[test]
fn a_header_without_do_not_edit_does_not_count() {
    let source = "// Generated from Expr.g4 by ANTLR 4.13.1\npackage com.example;\n";
    assert!(!is_generated(source));
}

#[test]
fn the_phrases_in_a_comment_after_code_do_not_count() {
    let source = "class C {}\n// Generated by hand. Do not edit without a review.\n";
    assert!(!is_generated(source));
}

#[test]
fn a_handwritten_file_is_not_generated() {
    let source = "/*\n * Copyright 2026 Example Ltd.\n * Licensed under the Apache License, Version 2.0.\n */\npackage com.example;\n\nclass C {}\n";
    assert!(!is_generated(source));
}
