[package]
name = "bonsai-cli"
description = "Command line interface for bonsai-lint"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[[bin]]
name = "bonsai"
path = "src/main.rs"

[features]
default = ["php", "ts"]
php = ["bonsai-lint/php"]
ts = ["bonsai-lint/ts"]

[dependencies]
bonsai-core = { workspace = true }
bonsai-lint = { workspace = true, default-features = false }
clap = { workspace = true }
serde_json = { workspace = true }

[lints]
workspace = true
