//! Python has no single generated-file convention, so the rule reads what the common generators
//! actually write before the first line of code: both "generated" and "do not edit".

use bonsai_lang_python::is_generated;

#[test]
fn a_protobuf_header_marks_a_file_generated() {
    let source = "# -*- coding: utf-8 -*-\n# Generated by the protocol buffer compiler.  DO NOT EDIT!\n# NO CHECKED-IN PROTOBUF GENCODE\n# source: orders.proto\n# Protobuf Python Version: 5.28.2\n\"\"\"Generated protocol buffer code.\"\"\"\nfrom google.protobuf import descriptor as _descriptor\n";
    assert!(is_generated(source));
}

#[test]
fn a_grpc_header_marks_a_file_generated() {
    let source = "# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!\n\"\"\"Client and server classes corresponding to protobuf-defined services.\"\"\"\nimport grpc\n";
    assert!(is_generated(source));
}

#[test]
fn a_multi_line_thrift_header_marks_a_file_generated() {
    let source = "#\n# Autogenerated by Thrift Compiler (0.19.0)\n#\n# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING\n#\n#  options string: py\n#\n\nfrom thrift.Thrift import TType\n";
    assert!(is_generated(source));
}

#[test]
fn crlf_a_byte_order_mark_a_shebang_and_any_case_still_match() {
    let crlf = "\u{feff}# generated by tooling\r\n# do NOT edit\r\nimport os\r\n";
    assert!(is_generated(crlf));

    let shebang = "#!/usr/bin/env python\n\n# Generated file. Do not edit.\nimport os\n";
    assert!(is_generated(shebang));
}

/// A Django migration says only "Generated": it is meant to be edited, and stays scored.
#[test]
fn a_django_migration_is_not_generated() {
    let source =
        "# Generated by Django 5.1 on 2026-09-26 10:00\n\nfrom django.db import migrations\n";
    assert!(!is_generated(source));
}

#[test]
fn the_phrases_after_the_first_line_of_code_do_not_count() {
    let source = "import os\n# Generated. DO NOT EDIT.\n";
    assert!(!is_generated(source));
}

#[test]
fn the_phrases_in_a_docstring_do_not_count() {
    let source = "\"\"\"Generated code. Do not edit.\"\"\"\nimport os\n";
    assert!(!is_generated(source));
}

#[test]
fn a_handwritten_file_is_not_generated() {
    let source = "# Copyright 2026 Example\n\"\"\"Orders.\"\"\"\n\nimport os\n";
    assert!(!is_generated(source));
}
